from bs4 import BeautifulSoup

from .scrape_container import ScrapeContainer

class ScraperSource:
    """Abstract class for handling scraper source implementations.
    """
    name: str

    def getLink(self, id) -> str:
        '''Returns a url based on the provided id, which was generated by the method isSupported(str)'''
        pass

    def isSupported(self, link) -> str:
        '''Identifies, if the given url is supported and returns a unique id'''
        return None

    def parse(self, container: ScrapeContainer, link: str, priority: int, id: str, soup: BeautifulSoup):
        '''Extracts all data which was provided by the given link'''
        pass